# Document:
# http://simiki.org/docs/configuration.html

root: /wiki/
url: kun.wiki
title: kun's wiki
keywords: wiki
description: kun's wiki 
author: kun

deploy:
  - type: git
    remote: 'origin'
    # branch: 'gh-pages'

pygments: true
theme: 'yasimple_x2'